### ISSUE TITLE
Compile in linux error

### ISSUE THREAD

**Issue by EmperYao** [cwbaker/forge#20] opened 2021-06-16 11:13 UTC
LuaSystem.cpp...
In file included from /root/forge/src/meow_hash/meow_intrinsics.h:34:0,
                 from LuaSystem.cpp:17:
/usr/lib/gcc/aarch64-linux-gnu/7.3.0/include/arm_neon.h: In function ‘meow_aes_128 Meow128_AESDEC(meow_aes_128, uint8x16_t)’:
/usr/lib/gcc/aarch64-linux-gnu/7.3.0/include/arm_neon.h:12433:1: error: inlining failed in call to always_inline ‘uint8x16_t vaesdq_u8(uint8x16_t, uint8x16_t)’: target specific option mismatch
 vaesdq_u8 (uint8x16_t data, uint8x16_t key)
 ^~~~~~~~~
In file included from LuaSystem.cpp:17:0:
/root/forge/src/meow_hash/meow_intrinsics.h:168:22: note: called from here
     R.A = vaesimcq_u8(vaesdq_u8(Prior.A, Prior.B));
           ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/forge/src/meow_hash/meow_intrinsics.h:34:0,
                 from LuaSystem.cpp:17:
/usr/lib/gcc/aarch64-linux-gnu/7.3.0/include/arm_neon.h:12447:1: error: inlining failed in call to always_inline ‘uint8x16_t vaesimcq_u8(uint8x16_t)’: target specific option mismatch
 vaesimcq_u8 (uint8x16_t data)
 ^~~~~~~~~~~
In file included from LuaSystem.cpp:17:0:
/root/forge/src/meow_hash/meow_intrinsics.h:168:22: note: called from here
     R.A = vaesimcq_u8(vaesdq_u8(Prior.A, Prior.B));
           ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
LuaTarget.cpp...

**Comment by cwbaker** [comment] 2021-06-17 07:28
Thanks Zhang.

The problem is that Forge isn't setup to compile for an ARM processor.  Are you building on a Raspberry Pi perhaps?

I'll try and setup the correct configuration tonight and send you through a branch to test.  I don't have any ARM hardware running Linux to test on myself.  But, in theory at least, if it compiles it should work okay.

Thanks,
Charles

**Comment by cwbaker** [comment] 2021-06-17 08:24
Actually I have a few questions:

1. What is the output of `lscpu` when run from the machine you're trying to compile on?
2. If you change `-march=native` to `-march=native+aes` in bootstrap-linux.bash and run what happens?

Assuming that you're trying to compile using bootstrap-linux.bash to start with.

Thanks,
Charles

**Comment by cwbaker** [comment] 2021-06-17 09:06
@EmperYao can you please try the code in the `compile-for-arm-processors` branch?  This might build with bootstrap-linux.bash and then build fully with the bootstrapped `forge`.

I'll need to tidy up those changes a bit but need to see if they work first.

Thanks again,
Charles

**Comment by EmperYao** [comment] 2021-06-17 09:26
Ok, I'll try and respond as soon as possible

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by cwbaker** [comment] 2021-06-18 09:18
Cheers for that.

I believe I have that working now.  The problem was that AES instructions weren't enabled when building for ARM.  Building and running on ARM has never been tested but I believe it should work.

Please can you try go through the installations steps with the `compile-for-arm-processors` branch checked out?  I've tidied that up now and once you can confirm that it works for you I'll push it to main.

Installation instructions (from [Installation](https://cwbaker.github.io/forge/installation/)):

From a shell with GCC installed and `~/bin` in `$PATH` the following should build `forge` and put it into `~/bin`:

~~~sh
git clone git@github.com:cwbaker/forge.git forge
cd forge
git checkout compile-for-arm-processors
git submodule update --init
bash ./bootstrap-linux.bash
./bootstrap/bin/forge variant=shipping install
ln -s ~/forge/bin/forge ~/bin/forge
~~~

Thanks,
Charles

**Comment by EmperYao** [comment] 2021-06-18 14:15
OK，i will have a try



发自我的小米手机
在 Charles Baker ***@***.***>，2021年6月18日 下午5:19写道：

Cheers for that.

I believe I have that working now. The problem was that AES instructions weren't enabled when building for ARM. Building and running on ARM has never been tested but I believe it should work.

Please can you try go through the installations steps with the compile-for-arm-processors branch checked out? I've tidied that up now and once you can confirm that it works for you I'll push it to main.

Installation instructions (from Installation<https://cwbaker.github.io/forge/installation/>):

From a shell with GCC installed and ~/bin in $PATH the following should build forge and put it into ~/bin:

git clone ***@***.***:cwbaker/forge.git forge
cd forge
git checkout compile-for-arm-processors
git submodule update --init
bash ./bootstrap-linux.bash
./bootstrap/bin/forge variant=shipping install
ln -s ~/forge/bin/forge ~/bin/forge

Thanks,
Charles

**Comment by EmperYao** [comment] 2021-06-18 14:44
emmm, this arm machine's core is Kunpeng 920-6426, made by Huawei.

**Comment by EmperYao** [comment] 2021-06-18 14:47
Sorry for that, the option -maes is not right.Error is that:
[
            ~/forge/src/boost/libs/system/src ~/forge
error_code.cpp...
g++: error: unrecognized command line option ‘-maes’
ar: *.o: No such file or directory
~/forge
boost_filesystem
~/forge/src/boost/libs/filesystem/src ~/forge
codecvt_error_category.cpp...
g++: error: unrecognized command line option ‘-maes’
operations.cpp...
g++: error: unrecognized command line option ‘-maes’
path.cpp...
g++: error: unrecognized command line option ‘-maes’
path_traits.cpp...
g++: error: unrecognized command line option ‘-maes’
portability.cpp...
g++: error: unrecognized command line option ‘-maes’
unique_path.cpp...
g++: error: unrecognized command line option ‘-maes’
utf8_codecvt_facet.cpp...
g++: error: unrecognized command line option ‘-maes’
windows_file_codecvt.cpp...
g++: error: unrecognized command line option ‘-maes’
ar: *.o: No such file or directory
]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by cwbaker** [comment] 2021-06-19 06:39
Okay. I've used a simpler hash function that removes the need for the AES instruction set. That change is merged to main now along with changes to build with the native architecture of the host.

Can you please try the installation steps again, this time from the main branch? Let me know how it goes.

Thanks,
Charles

**Comment by EmperYao** [comment] 2021-06-19 09:54
OK，i will try again



发自我的小米手机
在 Charles Baker ***@***.***>，2021年6月19日 下午2:39写道：

Okay. I've used a simpler hash function that removes the need for the AES instruction set. That change is merged to main now along with changes to build with the native architecture of the host.

Can you please try the installation steps again, this time from the main branch? Let me know how it goes.

Thanks,
Charles

**Comment by EmperYao** [comment] 2021-06-19 10:23
emmm， now i can compile this code in arm machine, thanks a lot

**Comment by EmperYao** [comment] 2021-06-19 10:25
Thanks a lot, I can compile this code in my arm macine now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Closed** 2021-06-19 10:25 UTC

**Comment by cwbaker** [comment] 2021-06-19 20:26
Glad to hear it.  Thanks for all your help and good luck!
